#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_INTERNAL_IP:8080
export JAVA_HOME=/usr/lib/jvm/java-1.7.0
$OPENSHIFT_REPO_DIR/diy/virgo/bin/startup.sh
